<header class="masthead -center">
    <div class="inner">
        <h1 class="-headline">MistTape</h1>
        <p>Use this site to post videos to <a href="http://apps.10covert.com/mixtape" target="_blank" class="-magenta -magenta-hover">Mixtape</a>. Post tracks from your personal Spotify playlists or search the Youtube API directly. Room notifications will be sent to the Mixtape HipChat room.</p>
    </div>
</header>