<section class="search" id="youtubeSearch">
    <form id="search-form" class="search__form pure-form pure-form-aligned -center">
        <fieldset>
            <input name="query" id="search-query" class="search__query" type="text" />
            <button type="submit" class="pure-button -magenta">Search YouTube</button>
        </fieldset>
    </form>
    <div id="search-results" class="search__results -left"></div>
</section>