<section id="spotify-view" class="-left -bg-green">
    <header class="playlists__masthead -center" id="playlist-header">
        <h1 class="-headline">Your Spotify Playlists</h1>
        <p>Click a playlist to view tracks.</p>
    </header>
    <div class="playlists"></div>
    <footer class="spotify__footer">
        <a class="load-more load-bar -bg-green -hover-white">Load More Playlists</a>
        <p class="loading-text load-bar -bg-green">Loading Playlists...</p>
    </footer>
</section>
