<section class="main-content" id="mainContent">
    <div id="main-view">
        <header class="spotify__header">
            <p>Click a playlist to view tracks or <a class="search-btn">search Youtube.</a></p>
        </header>
        <div class="spotify__playlists"></div>
        <footer class="spotify__footer">
            <a class="load-more load-bar">Load More Playlists</a>
            <p class="loading-text load-bar">Loading Playlists...</p>
        </footer>
    </div>
</section>